# -*- coding: utf-8 -*-
"""Parth sharma population analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jr4jdWxvFQwb22qVvAKAspmbcTBZE6XF
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Load the data

df_pop = pd.read_csv('API_SP.POP.TOTL_DS2_en_csv_v2_7.csv', skiprows=4)
df_meta = pd.read_csv('Metadata_Country_API_SP.POP.TOTL_DS2_en_csv_v2_7.csv')

# 2. Merge the files so we know which region each country belongs to
df_merged = pd.merge(df_pop, df_meta, on='Country Code')

# 3. Clean the data (remove groups like "World" that don't have a Region)
df_clean = df_merged.dropna(subset=['Region'])

# --- CHART 1: Bar Chart (Categorical) ---
plt.figure(figsize=(10, 6))
# Calculate total population per region for the year 2023
region_counts = df_clean.groupby('Region')['2023'].sum().sort_values(ascending=False)
sns.barplot(x=region_counts.index, y=region_counts.values, palette='viridis')
plt.title('Total Population by Region (2023)')
plt.xticks(rotation=45)
plt.ylabel('Population')
plt.show()

# --- CHART 2: Histogram (Continuous) ---
plt.figure(figsize=(10, 6))
# Show how population is distributed across different countries
sns.histplot(df_clean['2023'], bins=30, kde=True, color='skyblue')
plt.title('Distribution of Country Populations (2023)')
plt.xlabel('Population (Log Scale)')
plt.xscale('log') # We use a log scale because populations vary hugely
plt.show()